#pragma once
#include <GL\glut.h>
#include <iostream>
#include <string>
#include <GL/gl.h>
#include <GL/glut.h>
#include "Cube.h"
#include "Main.h"
#include "Plane.h"
#include "Viewports.h"
#include "utilities.h"
